### ISSUE TITLE
[BUG] Accessibility Checker scan "Needs review" total does not match the scan summary 

### ISSUE THREAD

**Issue by snidersd** [IBMa/equal-access#615]
## Accessibility Checker scan "Needs review" total does not match the scan summary

MacOS Monterey 12.0.1
Firefox 91.4.1esr (64-bit) or Chrome Version 97.0.4692.71 
Accessibility Checker 3.1.12 Ruleset: 17 November 2021 Deployment

## What tool(s) are you using?
- accessibility-checker-extension (In the Browser)

## Steps to reproduce the issue
1. Navigate to https://www.ibm.com/able/
2. Open the Accessibility Checker
3. Go to the Accessibility Assessment
4. Scan the page (see screen shot below on FF) and scan "Needs review" total does not match the scan summary.
<img width="1265" alt="40c71200-73ac-11ec-99b5-e968dc303b9d" src="https://user-images.githubusercontent.com/21676914/149233627-5a3039e2-9468-42de-902a-34fb2470d125.png">

This issue can be reproduced on Chrome. Also note, Issue found overlaps into the right panel in this view:
<img width="1315" alt="5859c700-73bb-11ec-9adf-d1e1b8fcb6ba" src="https://user-images.githubusercontent.com/21676914/149233703-8b9c7f9b-b716-4b42-b475-3aeeedecc764.png">

**Comment by tombrunet** [comment]
FYI @drjoho

**Comment by drjoho** [comment]
The mistake is only for the needs review in the scan summary. The rest of the numbers are correct. I will make a branch and correct it.

**Comment by drjoho** [comment]
![image](https://user-images.githubusercontent.com/64442976/151307389-aff997b4-56cd-4837-b551-05a79f0d62b1.png)

**Comment by drjoho** [comment]
Fixed - same error in scans also fixed. Ready for QA

**Comment by drjoho** [comment]
PR #625

**Comment by eirckr** [comment]
The issue is still present with https://github.com/IBMa/equal-access/actions/runs/1754877517

**Comment by eirckr** [comment]
Validated
